version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: coffee_db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  coffee:
    build: work_project/
    restart: always
    ports:
      - 8000:8000
    environment:
      WAIT_HOSTS: db:5432
    
