# Generated by Django 3.2.4 on 2021-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название кофе')),
                ('value', models.FloatField(default=0.2, verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Кофе',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField(unique=True, verbose_name='Заказ')),
                ('status', models.CharField(default='Ожидает', max_length=15, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shop', models.IntegerField(unique=True, verbose_name='Номер торговой точки')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название торговой точки')),
                ('location', models.CharField(max_length=150, verbose_name='Адрес торговой точки')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
            },
        ),
    ]
