# Generated by Django 3.2.4 on 2021-06-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='id_shop',
        ),
        migrations.AddField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coffee.shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Ждет оплаты', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
