# Generated by Django 3.2.4 on 2021-06-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20210611_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.coffee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.shop'),
        ),
    ]
