# Generated by Django 3.2.4 on 2021-06-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20210611_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_shop',
        ),
        migrations.AddField(
            model_name='coffee',
            name='cost',
            field=models.IntegerField(default=100, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.order'),
        ),
        migrations.AddField(
            model_name='shop',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.order'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='value',
            field=models.FloatField(verbose_name='Объем'),
        ),
    ]
