# Generated by Django 3.2.4 on 2021-06-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20210615_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffee.shop'),
        ),
    ]
