# Generated by Django 3.2.4 on 2021-06-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20210615_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coffee',
            new_name='Выберите напиток',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shop',
            new_name='Откуда заберете',
        ),
    ]
