# Generated by Django 3.2.4 on 2021-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20210615_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='number_phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Введите номер телефона'),
        ),
    ]
