# Generated by Django 3.2.4 on 2021-06-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20210615_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Выберите напиток',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Откуда заберете',
        ),
        migrations.AddField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee', verbose_name='Выберите напиток'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffee.shop', verbose_name='Откуда заберете'),
        ),
    ]
