# Generated by Django 3.2.4 on 2021-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_order_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название кофе'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='value',
            field=models.CharField(max_length=5, verbose_name='Объем'),
        ),
    ]
